# Generated by Django 4.2.21 on 2025-06-18 07:06

import django.core.validators
from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inversiones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inversiones'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default=1, help_text='Formato: 12.345.678-9', max_length=12, unique=True, validators=[usuarios.models.validar_rut_chileno], verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='saldo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tarjetas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarjetas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
    ]
