# Generated by Django 4.2.21 on 2025-06-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_email_alter_customuser_rut_and_more'),
    ]

    operations = [
    ]
