# Generated by Django 4.2.21 on 2025-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_customuser_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'Google Authenticator'), ('email', 'Código por correo')], default='totp', max_length=10),
        ),
    ]
