# Generated by Django 4.2.21 on 2025-06-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_customuser_mfa_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'Google Authenticator - ¡Descarga la aplicación! (Recomendado para mayor seguridad)'), ('email', 'Código por correo')], default='totp', max_length=10),
        ),
    ]
